"kr-vs-kp": 
  "url": "https://www.openml.org/data/download/3/dataset_3_kr-vs-kp.arff"
  "label": "class"
"spambase": 
  "url": "https://www.openml.org/data/download/44/dataset_44_spambase.arff"
  "label": "class"
"yeast_ml8": 
  "url": "https://www.openml.org/data/download/52220/phpHvRukp"
  "label": "class14"
"abalone": 
  "url": "https://www.openml.org/data/download/53254/abalone.arff"
  "label": "binaryClass"
"credit-g": 
  "url": "https://www.openml.org/data/download/31/dataset_31_credit-g.arff"
  "label": "class"
"puma32H": 
  "url": "https://www.openml.org/data/download/53286/puma32H.arff"
  "label": "binaryclass"
"cpu_small": 
  "url": "https://www.openml.org/data/download/53269/cpu_small.arff"
  "label": "binaryclass"
"delta_ailerons": 
  "url": "https://www.openml.org/data/download/53337/delta_ailerons.arff"
  "label": "binaryclass"
"2dplanes": 
  "url": "https://www.openml.org/data/download/53261/2dplanes.arff"
  "label": "binayclass"
"electricity": 
  "url": "https://www.openml.org/data/download/2419/electricity-normalized.arff"
  "label": "class"
