"kr-vs-kp": 
  "url": "https://www.openml.org/data/download/3/dataset_3_kr-vs-kp.arff"
  "label": "class"
"spambase": 
  "url": "https://www.openml.org/data/download/44/dataset_44_spambase.arff"
  "label": "class"
"yeast_ml8": 
  "url": "https://www.openml.org/data/download/52220/phpHvRukp"
  "label": "class14"
"abalone": 
  "url": "https://www.openml.org/data/download/53254/abalone.arff"
  "label": "binaryClass"
"bank32nh": 
  "url": "https://www.openml.org/data/download/53367/bank32nh.arff"
  "label": "binaryClass"
"puma32H": 
  "url": "https://www.openml.org/data/download/53286/puma32H.arff"
  "label": "binaryClass"
"cpu_small": 
  "url": "https://www.openml.org/data/download/53269/cpu_small.arff"
  "label": "binaryClass"
"delta_ailerons": 
  "url": "https://www.openml.org/data/download/53337/delta_ailerons.arff"
  "label": "binaryClass"
"2dplanes": 
  "url": "https://www.openml.org/data/download/53261/2dplanes.arff"
  "label": "binaryClass"
"electricity": 
  "url": "https://www.openml.org/data/download/2419/electricity-normalized.arff"
  "label": "class"
